/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenders: Tender;
    gallery: Gallery;
    activities: Activity;
    campaigns: Campaign;
    news: News;
    events: Event;
    'tender-categories': TenderCategory;
    'annual-reports': AnnualReport;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenders: TendersSelect<false> | TendersSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'tender-categories': TenderCategoriesSelect<false> | TenderCategoriesSelect<true>;
    'annual-reports': AnnualReportsSelect<false> | AnnualReportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'events-page': EventsPage;
    'tenders-page': TendersPage;
    'annual-reports-page': AnnualReportsPage;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'events-page': EventsPageSelect<false> | EventsPageSelect<true>;
    'tenders-page': TendersPageSelect<false> | TendersPageSelect<true>;
    'annual-reports-page': AnnualReportsPageSelect<false> | AnnualReportsPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders".
 */
export interface Tender {
  id: string;
  title: string;
  /**
   * Optional ID/File number (e.g., NEZCC/2024/01)
   */
  referenceId?: string | null;
  category: string | TenderCategory;
  releaseDate: string;
  /**
   * Optional closing/deadline date
   */
  closingDate?: string | null;
  status: 'active' | 'closing_soon' | 'closed';
  document: string | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the available categories for Advertisements and Tenders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tender-categories".
 */
export interface TenderCategory {
  id: string;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  title: string;
  type: 'image' | 'video';
  media?: (string | null) | Media;
  videoUrl?: string | null;
  date: string;
  /**
   * Used for manual sorting, higher numbers appear first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Past cultural activities and highlights with cover images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  title: string;
  /**
   * URL friendly name (e.g., my-activity-name)
   */
  slug: string;
  coverImage?: (string | null) | Media;
  eventDate?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Large banner slides displayed in the hero carousel at the top of the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: string;
  title: string;
  description: string;
  image: string | Media;
  link?: string | null;
  linkText?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Latest updates and announcements shown in the news section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * A short summary to display on the homepage cards
   */
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage: string | Media;
  /**
   * Check this to feature the article as the large card on the homepage
   */
  isFeatured?: boolean | null;
  publishedDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Scheduled events with dates, times, and venue maps (e.g. Upcoming Events).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  startDate: string;
  location: string;
  /**
   * e.g., 10:00 AM - 6:00 PM
   */
  time: string;
  featuredImage: string | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Add up to 3 highlights for the event
   */
  highlights?:
    | {
        /**
         * Material symbols icon name (e.g., music_note, festival, restaurant)
         */
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Google Maps embed link or regular URL
   */
  venueMapLink?: string | null;
  ticketing?: {
    /**
     * e.g., Free Entry, $50, etc.
     */
    ticketPrice?: string | null;
    registrationRequired?: boolean | null;
    /**
     * URL for purchasing tickets or registering
     */
    registrationLink?: string | null;
  };
  eventActions?: {
    calendarLink?: string | null;
    shareLink?: string | null;
    customLink?: string | null;
    contactEmail?: string | null;
  };
  sponsors?:
    | {
        name: string;
        logo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-reports".
 */
export interface AnnualReport {
  id: string;
  title: string;
  financialYear: string;
  publishedDate: string;
  description: string;
  coverImage?: (string | null) | Media;
  document: string | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tenders';
        value: string | Tender;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: string | Campaign;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'tender-categories';
        value: string | TenderCategory;
      } | null)
    | ({
        relationTo: 'annual-reports';
        value: string | AnnualReport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders_select".
 */
export interface TendersSelect<T extends boolean = true> {
  title?: T;
  referenceId?: T;
  category?: T;
  releaseDate?: T;
  closingDate?: T;
  status?: T;
  document?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  type?: T;
  media?: T;
  videoUrl?: T;
  date?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  eventDate?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  link?: T;
  linkText?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  content?: T;
  featuredImage?: T;
  isFeatured?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  location?: T;
  time?: T;
  featuredImage?: T;
  content?: T;
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  venueMapLink?: T;
  ticketing?:
    | T
    | {
        ticketPrice?: T;
        registrationRequired?: T;
        registrationLink?: T;
      };
  eventActions?:
    | T
    | {
        calendarLink?: T;
        shareLink?: T;
        customLink?: T;
        contactEmail?: T;
      };
  sponsors?:
    | T
    | {
        name?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tender-categories_select".
 */
export interface TenderCategoriesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-reports_select".
 */
export interface AnnualReportsSelect<T extends boolean = true> {
  title?: T;
  financialYear?: T;
  publishedDate?: T;
  description?: T;
  coverImage?: T;
  document?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage visibility of sections and texts on the main home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  heroTitle?: string | null;
  heroDescription?: string | null;
  aboutTitle?: string | null;
  aboutDescription?: string | null;
  showSchemes?: boolean | null;
  showInformationCategories?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage banners and titles for the Calendar of Events page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page".
 */
export interface EventsPage {
  id: string;
  /**
   * The main title displayed at the top of the Events page.
   */
  pageTitle?: string | null;
  banners?:
    | {
        title: string;
        image?: (string | null) | Media;
        /**
         * Where should this banner link to? (e.g., /library, https://example.com)
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the hero section and general instructions for the Advertisement & Tenders page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders-page".
 */
export interface TendersPage {
  id: string;
  heroTitle: string;
  heroDescription?: string | null;
  /**
   * Background image for the top hero section.
   */
  heroImage?: (string | null) | Media;
  contactTitle: string;
  contactPhone?: string | null;
  contactEmail?: string | null;
  noticesTitle: string;
  noticesList?:
    | {
        noticeText: string;
        /**
         * Optional URL if this notice should be clickable
         */
        noticeLink?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-reports-page".
 */
export interface AnnualReportsPage {
  id: string;
  heroTitle: string;
  heroDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  aboutTitle?: T;
  aboutDescription?: T;
  showSchemes?: T;
  showInformationCategories?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-page_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  pageTitle?: T;
  banners?:
    | T
    | {
        title?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenders-page_select".
 */
export interface TendersPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  contactTitle?: T;
  contactPhone?: T;
  contactEmail?: T;
  noticesTitle?: T;
  noticesList?:
    | T
    | {
        noticeText?: T;
        noticeLink?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-reports-page_select".
 */
export interface AnnualReportsPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}